# 开启 TLS
#server:
#  ssl:
#    # 生成秘钥文件
#    # keytool -genkeypair -alias architect-analysis-actuator \
#    # -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore keystore.p12 -validity 3650 -storepass 123456
#    # 查看秘钥信息 keytool -list -v -storetype pkcs12 -keystore keystore.p12
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: architect-analysis-actuator

# endpoint 管理
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    # HealthEndpointProperties
    health:
      show-details: always
      group:
        custom:
          include: simple
#  server:
#    # 管理站点的访问地址修改
#     address: 127.0.0.2
#    # 启用ssl之后,端口分离
#     port: 9002
#     ssl:
#      enabled: false

# info endpoint 内容
info:
  app:
    encoding: @project.build.sourceEncoding@
  java:
    source: @java.version@
  target: @java.version@

# endpoint 在jmx上开启
spring:
  jmx:
    enabled: true