spring:
  application:
    name: 02-rocket-mq

# 查阅rocketmq的spring-configuration-metadata.json
rocketmq:
  name-server: 10.253.2.56:9876
  producer:
    group: yufr-producer
    # 由于机器性能差,超时时间需要放大
    sendMessageTimeout: 600000
    # 信息轨迹 默认是开启的
    customized-trace-topic: my-trace-topic
  consumer:
    group: yufr-consumer
    topic: test-topic-3