logging:
  level:
    indi.biz.yufr.config.MyMetaObjectHandler: debug

---
spring:
  profiles: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ksAuth?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root

---
spring:
  profiles: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=Mysql;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: sa
  #    initialization-mode: never
  h2:
    console:
      enabled: true

---
spring:
  profiles: oracle
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.243.141.139:1521:orcl
    username: wolf
    password: wolf